### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by JayantGoel001** [Bash-Woman-Community/Support#10]
Please invite me to the GitHub Community Organisation. 

- #### Name: Jayant Goel

- #### Discord Username(if exists): 

- #### Additional Context:

To contribute towards open source community

**Comment by JayantGoel001** [comment]
@seema1711 
Thanks In Advance

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
