### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by mdPial** [Bash-Woman-Community/Support#11]
Please invite me to the GitHub Community Organisation. 

- #### Name: Md. Pial Ahamed

- #### Discord Username(if exists): mdPial#5027

From LinkedIn

I love to contribute to the open source community. Also being a member  will push me hard to get out of my comfort zone when any task will come. I have seen in discord how much response people give if someone asks anything. So, I have chosen to be a part of this community also Bash Woman Community is new so I will learn many things.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.

**Comment by mdPial** [comment]
Thank You 😃
