### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by Sam8239** [Bash-Woman-Community/Support#13]
Please invite me to the GitHub Community Organisation. 

- #### Name: Shubham Samanta

- #### Discord Username(if exists): 
Shubham Samanta#4485

- #### Additional Context:
 Through Aditya Oberai.

 I want to help and improve mutual productivity.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
