### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by kritikaparmar-programmer** [Bash-Woman-Community/Support#14]
Please invite me to the GitHub Community Organisation. 

- #### Name: Kritika Parmar

- #### Discord Username(if exists): Kritika#9578

- #### Additional Context:
How you came to know about this community?
I came to know about the community through Twitter. I would love to join and give my contributions to this community.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
