### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by Prince-Shivaram** [Bash-Woman-Community/Support#18]
Please invite me to the GitHub Community Organisation. 

- #### Name: J. Siv Ram Shastri

- #### Discord Username(if exists): J. Siv Ram Shastri

- #### Additional Context: 

I would love to contribute to this amazing community and interested in helping beginners as well.

I came to know about this community through one of my GitHub connections.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.

**Comment by Prince-Shivaram** [comment]
Thank you!
