### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by akshitagupta15june** [Bash-Woman-Community/Support#2]
Please invite me to the GitHub Community Organisation. 

- #### Name: Akshita Gupta

- #### Additional Context: Bashwoman Youtube channel
 

 I would love to be a part of this community for contributing in open source!!

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.

**Comment by akshitagupta15june** [comment]
Thanks @seema1711
