### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by Priya96-sketch** [Bash-Woman-Community/Support#20]
Please invite me to the GitHub Community Organisation. 

- #### Name: Priya Mondal

- #### Discord Username(if exists): Priya#6559

- #### Additional Context:
     --> How you came to know about this community? From LinkedIn, I came to know about this community.

Why do you want to join? 
   --> To contribute more to diverse open-source projects, to gain more skills as well as sharpen my tech stacks, and last, but 
     not least, to help in varied aspects for the society.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.

**Comment by Priya96-sketch** [comment]
Thank You!
