### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by kumarankm** [Bash-Woman-Community/Support#21]
Please invite me to the GitHub Community Organisation. 

- #### Name: Kumaran KM

- #### Discord Username(if exists): Kumaran KM #8512

- #### Additional Context:

I came across youtube and later I have joined the discord server and I have noticed that there are many active people in there. So I think this will be a better community for me to explore more about open source

Just now I started my open source journey. I'm a complete beginner, so I think this community will help me to mark the next level.

**Comment by seema1711** [comment]
Please add additional info.

**Comment by kumarankm** [comment]
@seema1711 Yeah done!

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. You may close this issue now.
