### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by japneetbhatia** [Bash-Woman-Community/Support#23]
Please invite me to the GitHub Community Organisation. 

- #### Name: Japneet Kaur Bhatia

- #### Discord Username(if exists): japneetkaur#3904

- #### Additional Context:

I came to know about this community through my friends. I want to join and contribute to community. I want to enhance my skills and want to learn more about tech.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
