### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by PulkitSinghDev** [Bash-Woman-Community/Support#24]
Please invite me to the GitHub Community Organisation. 

- #### Name: Pulkit Singh

**Comment by seema1711** [comment]
Please add some details.

**Comment by PulkitSinghDev** [comment]
Can you please specify 🙏😊

**Comment by seema1711** [comment]
Like this https://github.com/Bash-Woman-Community/Support/issues/28#issue-818125946.

**Comment by PulkitSinghDev** [comment]
Name:- Pulkit Singh
Discord User name:- Pulkit Singh#8120
Reason behind joining the community:- currently working on helping and contributing to various communities and I love this and I would like to do same at Bash Woman Community :)

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close this issue now.
