### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by viraldevpb** [Bash-Woman-Community/Support#25]
Please invite me to the GitHub Community Organisation. 

- #### Name: Prathamesh Borse

- #### Discord Username(if exists):  Pratham#3453

- #### Additional Context: I came to know about this community on the MLH Local Hack Day Build Hackathon and also from  Eddie Jaoude on EddieHub Discord Channel from then I am following Seema Saharan on Twitter and also on Youtube As Well.!

I want to join this community because I want to contribute to this community. I have a hunger to contribute to Open Source and its communities more and More.👨‍💻😍

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.

**Comment by viraldevpb** [comment]
Thank You @seema1711 for Inviting me to the Community. Can't wait to make a contribution to the Community.
