### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by riturajjain2000** [Bash-Woman-Community/Support#27]
Please invite me to the GitHub Community Organisation. 

- #### Name: Rituraj Jain

- #### Discord Username(if exists): riturajjain2000#8045

- #### Additional Context: I love giving it back to the community and be of some help! 😄😄

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.

**Comment by riturajjain2000** [comment]
Thanks for the invite!
