### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by Kushal997-das** [Bash-Woman-Community/Support#28]
`Please invite me to the GitHub Community Organisation.`

Name: Kushal Das
Discord Username(if exists): Kushal Das#6121
Additional Context: I love giving it back to the community and be of some help! 
Thank you :)

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close this issue now.

**Comment by Kushal997-das** [comment]
> Invite sent. Welcome to the community. ❤
> You may close this issue now.

Thanks @seema1711 ❤
