### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by flyingsonu122** [Bash-Woman-Community/Support#29]
Please invite me to the GitHub Community Organisation. 

- #### Name: Sonu Kumar Kushwaha

- #### Discord Username: flyingsonu736#2119

- #### Additional Context:

From @seema1711 twitter handle

Passionate about **learning** and **educating** others in the field of innovation and technology

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close this issue now.

**Comment by flyingsonu122** [comment]
Thank you @seema1711
