### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by ritiksoni00** [Bash-Woman-Community/Support#3]
Please invite me to the GitHub Community Organisation.

- #### Name: Ritik Soni

- #### Discord Username(if exists): RTK

I LOVE TO BE IN COMMUNITIES THAT HELPS OTHERS AND MEET NEW PEOPLE ..GG

**Comment by ritiksoni00** [comment]
@seema1711  .... hola

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
