### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by ankitaggarwal23** [Bash-Woman-Community/Support#30]
Please invite me to the GitHub Community Organisation.

- #### Name: Ankit Aggarwal

- #### Discord Username: Ankit Aggarwal#2811
🤓

**Comment by seema1711** [comment]
Can you tell us why you want to join the community? What value will you add?

**Comment by seema1711** [comment]
This issue is not active, so I am closing it. If you want to be included, make a new issue. Thanks!
