### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by Surajbokde** [Bash-Woman-Community/Support#32]
Please invite me to the GitHub Community Organisation. 

- #### Name: Suraj Bokde

- #### Discord Username(if exists):  suraj#3042

**Comment by seema1711** [comment]
Can you tell us why you want to join the community? What value will you add?

**Comment by Surajbokde** [comment]
@seema1711  I loves the way community helps an individual ,in building up his career . I want to be part of this community by helping others and I have significant experience with them. I believe I can add value by helping people map their student dev life.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
Do introduce yourself in Discord and if you want to become a mentor do let us know there too.
