### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by HariAcidReign** [Bash-Woman-Community/Support#38]
Please invite me to the GitHub Community Organisation!

- #### Name: Hariharan

- #### Discord Username(if exists: HariAcidReign#3665
 

- #### Additional Context:

Came to know from Github and Linkedin

To be a part of a fast-growing OSS group and contribute code to.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
Do introduce yourself in Discord and if you want to become a mentor do let us know there too.
