### ISSUE TITLE
[Invite me to the Community] 😀

### ISSUE THREAD

**Issue by anjali1102** [Bash-Woman-Community/Support#39]
Please invite me to the GitHub Community Organisation. 

- #### Name: Anjali Chauhan

- #### Discord Username(if exists): 

- #### Additional Context:
I came to know about this community from Twitter, Friends

 I want to join because ma'am's videos make me learn new things. So, I would love to join her community. 😊

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
Do introduce yourself in Discord and if you want to become a mentor do let us know there too.
