### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by harshita19244** [Bash-Woman-Community/Support#4]
Please invite me to the GitHub Community Organisation. 

I would like to contribute to Data Structure related problems. I am also a web developer, so I can contribute to issues faced in web dev

- #### Name: Harshita Srinivas

- #### Discord Username(if exists): -

- #### Additional Context: I got to know about this community while exploring repos on GitHub

I love to contribute to open source projects, and engage with new communities. I believe that this will improve my skills, while also giving back to the community at the same time

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.

**Comment by harshita19244** [comment]
Thank You!
