### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by aryashah2k** [Bash-Woman-Community/Support#40]
Please invite me to the GitHub Community Organisation. 

- #### Name: Arya Shah

- #### Discord Username(if exists): Arya Shah#6453

- #### Additional Context:

From an existing member of the community.

To contribute and share the goal of helping 10k people by 2021.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
Do introduce yourself in Discord and if you want to become a mentor do let us know there too.

**Comment by aryashah2k** [comment]
Thank you for the Invite, shall join the Discord Server right away. Happy to be accepted into this organization.
