### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [Bash-Woman-Community/Support#41]
Please invite me to the GitHub Community Organisation. 

- #### Name:
Kaiwalya Koparkar

- #### Discord Username(if exists): 

Kaiwalya Koparkar#0747

- #### Additional Context:

EddiHub

I would love to explore more about technology

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
Do introduce yourself in Discord and if you want to become a mentor do let us know there too.

**Comment by kaiwalyakoparkar** [comment]
Thank you very much! I have already joined the discord channel!
