### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by riddhi-jain** [Bash-Woman-Community/Support#42]
Please invite me to the GitHub Community Organisation. 

I would love to be a part of the community in order to help others however I can and learn new things the other hand.

- #### Name: Riddhi Jain

- #### Discord Username(if exists): riddhi-jain

- #### Additional Context: Got to know about this community via Github itself.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now. 
Do introduce yourself in Discord and if you want to become a mentor do let us know there too.
