### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by Tarun-Kamboj** [Bash-Woman-Community/Support#44]
Please invite me to the GitHub Community Organisation. 

- #### Name: Tarun

- #### Discord Username(if exists):  Tarun#0089
  The username has two zeros before 89, somehow not showing above

- #### Additional Context:

Came to know about the community from Linkedin and would like to be a part of this community and contribute.

**Comment by Tarun-Kamboj** [comment]
@seema1711 please respond.

**Comment by seema1711** [comment]
Can you mention how will you contribute to the community? Any ideas?
