### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by yashsehgal** [Bash-Woman-Community/Support#46]
Please invite me to the GitHub Community Organisation. 
I would love to join this community.

- #### Name: Yash Sehgal

- #### Discord Username(if exists): yashsehgal#4591

- #### Additional Context:

Through a YouTube video.

I would love to grow with the community, network with folks and contribute at the best of my ability.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
Do introduce yourself in Discord and if you want to become a mentor do let us know there too.

**Comment by yashsehgal** [comment]
Thanks, @seema1711 😺
