### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by prathimacode-hub** [Bash-Woman-Community/Support#49]
Please invite me to the GitHub Community Organisation. 

- #### Name: Prathima Kadari

- #### Discord Username(if exists): Prathima Kadari#2069

- #### Additional Context:
I came to know about this community through youtube.

I want to grow with community, contribute to open source and network with like minded pals.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
Do introduce yourself in Discord and if you want to become a mentor do let us know there too.
