### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by geekquad** [Bash-Woman-Community/Support#5]
Please invite me to the GitHub Community Organisation. 

- #### Name: Aditya Kumar Gupta

- #### Discord Username(if exists):  Geekquad#0299

- #### Additional Context:
How you came to know about this community?
From a friend.

Why do you want to join?
This community is very active and will help me in my personal growth.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.

**Comment by geekquad** [comment]
Thankyou ma'am.
