### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by nilisha-jais** [Bash-Woman-Community/Support#50]
Please invite me to the GitHub Community Organisation. 

- #### Name: Nilisha Jaiswal

- #### Discord Username(if exists): Nilisha_#7378

- #### Additional Context:

I came to know about the community through Twitter

I believe in the power of community and hence wish to join the Bash Woman Community so that I can contribute more to diverse open-source projects and gain skills to sharpen my tech stacks at the same time

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
Do introduce yourself in Discord and if you want to become a mentor do let us know there too.
