### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by krishdevdb** [Bash-Woman-Community/Support#51]
Please invite me to the GitHub Community Organisation. 

- #### Name: Krish Gupta

- #### Discord Username(if exists): Krish Dev DB#4733

- #### Additional Context:

**Comment by seema1711** [comment]
Please include why you want to join the community and what value will you add.

**Comment by krishdevdb** [comment]
Hi, @seema1711 I want to be a member of this community to show support this community. I think this community is as awesome as EddieHub. I would love to be a part of this community. I saw this community at [EddieHub](eddiehub.org). I would love to be a member of this community and learn many new things 🙂. I am going to try to be the most active and supportive member of this community! To a community active community members are the most valuable things. 🙂

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now. Do introduce yourself in Discord and if you want to become a mentor do let us know there too. Share this on your socials, we would love to see that. Don't forget to tag us!

**Comment by krishdevdb** [comment]
> Do introduce yourself in Discord and if you want to become a mentor, let us know there too. Share this on your socials, we would love to see that. Don't forget to tag us!

Sure ❤️
