### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by mindninjaX** [Bash-Woman-Community/Support#52]
Please invite me to the GitHub Community Organisation. 

- #### Name: Rishabh Singh

- #### Discord Username(if exists): 

- #### Additional Context:

I would love to join the Bash Women Community because of the impact they have been making the community. Helping people rise up above their average potential and do something really amazing with the community. I have been active a lot in the community for quite some time now and I think this is the perfect time for me to start working on projects everyone can use and be benefited from. I plan to start some group projects on various topics and help other programmers who are new to all the open-source thing. So that they don't have to go through all the struggle and confusion I had to go through. I know how it feels to be alone as there is no one to guide you. You can bring the best of the best to the table, but with a lack of guidance and mentorship, nobody will even care. But this is something that can be changed. And it's already started by Bash Women and other amazing communities I am part of. I am not a genius or a pro-level hacker or something, but I am passionate and I have been there. And I don't want anyone else to go through all of it.

**Comment by seema1711** [comment]
Please include why you want to join the community and what value will you add.

**Comment by mindninjaX** [comment]
@seema1711 I have updated the proposal, please have a look.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
Do introduce yourself in Discord and if you want to become a mentor do let us know there too.
