### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by Aniket762** [Bash-Woman-Community/Support#54]
Please invite me to the GitHub Community Organisation. 

- #### Name: Aniket Pal

- #### Discord Username:  Aniket#9490

Why do you want to join?
I want to learn more from being in the community and I am organizing a Hackathon HackOdisha and want it to be the largest in Eastern India and being in the community will my dream easy to fulfill.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
Do introduce yourself in Discord and if you want to become a mentor do let us know there too.
