### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by Jassi10000** [Bash-Woman-Community/Support#6]
Please invite me to the GitHub Community Organisation. 

- #### Name: Jaskeerat Singh

- #### Discord Username(if exists): 
Jassi#8109
- #### Additional Context:
I came to know about this community while surfing through Github looking for exciting communities to join

I want to polish my existing skills and learn some new more , and I think being a part of Bash-Woman-Community would help me achieve that

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.

**Comment by Jassi10000** [comment]
Thanks @seema1711 for this opportunity 😍
