### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by diyajaiswal11** [Bash-Woman-Community/Support#7]
Please invite me to the GitHub Community Organisation. 

- #### Name: Diya Jaiswal

- #### Discord Username(if exists): Diya Jaiswal#5680

- #### Additional Context:

From a friend. 

I aim to unleash my potential to the best of my capabilities and I believe that this community will help me achieve the same.

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.
