### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by jbampton** [Bash-Woman-Community/Support#8]
Please invite me to the GitHub Community Organisation. 

Hello.  I like the ladies.  Would love an invite !!

- #### Name:  

John Bampton

- #### Discord Username(if exists): 
I am already a proud member of the Discord  Bash Woman Community 🚀 

- #### Additional Context:

Another GitHub friend is a member. 

- #### Why do you want to join?

To learn and teach others -> git push --force

**Comment by hardikk2002** [comment]
I would also love to be part of this community and I hope I will be a valuable asset to this community.😊
