### ISSUE TITLE
[Invite me to the Community]

### ISSUE THREAD

**Issue by TawfikYasser** [Bash-Woman-Community/Support#9]
Please invite me to the GitHub Community Organisation. 

- #### Name: Tawfik Yasser

- #### Discord Username(if exists): 

- #### Additional Context:

From other GitHub users.

I want to be a member of the great communities.

Thanks

**Comment by seema1711** [comment]
Invite sent. Welcome to the community. ❤
You may close the issue now.

**Comment by TawfikYasser** [comment]
Oh thanks a lot @seema1711
